authors:
  webdev:
    name: Web Dev Team
    description: Spokane Mountaineers
    avatar: https://github.com/Spokane-Mountaineers.png
  ecomm:
    name: Club Store
    description: Spokane Mountaineers
    avatar: https://github.com/Spokane-Mountaineers.png
